#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

nitrogen --restore &

polybar bar -r &

bspc monitor -d I II III IV V VI VII VIII 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color '#585858'
bspc config focused_border_color '#ebdbb2' #d65d0e


